import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for the AI Coloring Page Generator. Learn about usage rules, intellectual property, and limitations.",
  alternates: {
    canonical: "/terms-of-service",
  },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#FFF9F2]">
      <div className="max-w-[800px] mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <a href="/" className="inline-flex items-center gap-2 font-display text-[#FF6B4A] font-semibold mb-8 no-underline hover:text-[#E55A3A] transition-colors">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M19 12H5M12 19l-7-7 7-7" />
          </svg>
          Back to Home
        </a>

        <h1 className="font-display text-[32px] sm:text-[40px] font-semibold text-[#3D2C24] mb-8">
          Terms of Service
        </h1>
        <p className="text-[#8C7A6E] mb-8">Last updated: June 2026</p>

        <div className="prose prose-lg max-w-none text-[#3D2C24] space-y-6">
          <h2 className="font-display text-2xl font-semibold mt-10 mb-4">1. Acceptance of Terms</h2>
          <p>By accessing or using the AI Coloring Page Generator (&quot;the Service&quot;), you agree to these Terms of Service. If you do not agree, do not use the Service.</p>

          <h2 className="font-display text-2xl font-semibold mt-10 mb-4">2. Description of Service</h2>
          <p>The AI Coloring Page Generator allows users to create printable coloring pages by describing what they want using natural language prompts. The Service uses artificial intelligence to generate line-art images based on user prompts.</p>

          <h2 className="font-display text-2xl font-semibold mt-10 mb-4">3. User Conduct</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Submit prompts that generate illegal, harmful, or NSFW content</li>
            <li>Attempt to reverse engineer or abuse the AI generation system</li>
            <li>Use automated tools to spam or overload the Service</li>
            <li>Resell or redistribute generated content as stock assets (personal use only)</li>
          </ul>

          <h2 className="font-display text-2xl font-semibold mt-10 mb-4">4. AI-Generated Content</h2>
          <p>Coloring pages are generated by AI models. We do not guarantee that generated content is free of copyrighted elements. You are responsible for how you use generated pages. Read our <a href="/ai-disclaimer" className="text-[#FF6B4A] underline">AI Disclaimer</a> for more details.</p>

          <h2 className="font-display text-2xl font-semibold mt-10 mb-4">5. Free Usage</h2>
          <p>The Service is free with daily generation limits. We reserve the right to modify usage limits at any time. Current limits: 5 generations/day without signup, 10/day with free registration.</p>

          <h2 className="font-display text-2xl font-semibold mt-10 mb-4">6. Intellectual Property</h2>
          <p>The AI Coloring Page Generator brand, website, and underlying code are owned by us. Generated coloring pages are for personal, non-commercial use.</p>

          <h2 className="font-display text-2xl font-semibold mt-10 mb-4">7. Disclaimer of Warranties</h2>
          <p>The Service is provided &quot;as is&quot; without warranties of any kind. We do not guarantee uninterrupted or error-free operation.</p>

          <h2 className="font-display text-2xl font-semibold mt-10 mb-4">8. Limitation of Liability</h2>
          <p>We shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.</p>

          <h2 className="font-display text-2xl font-semibold mt-10 mb-4">9. Termination</h2>
          <p>We reserve the right to terminate or suspend access to the Service at our discretion, without prior notice, for conduct that violates these Terms.</p>

          <h2 className="font-display text-2xl font-semibold mt-10 mb-4">10. Contact</h2>
          <p>Questions? Contact us at <a href="mailto:hello@aicoloringgenerator.com" className="text-[#FF6B4A] underline">hello@aicoloringgenerator.com</a>.</p>
        </div>
      </div>
    </div>
  );
}
